rootProject.name = 'otus_arch_and_patterns'
include 'QuadraticEquation'
include 'GameAbstraction'
include 'GameException'
include 'Command'
include 'Ioc'
include 'Adapter'
include 'Event-loop'
include 'Message'
include 'Auth'
include 'Auth:auth-server'
findProject(':Auth:auth-server')?.name = 'auth-server'
include 'Auth:game-server'
findProject(':Auth:game-server')?.name = 'game-server'
include 'State'